log:
  level: "debug"
  mode: "dev"

grpc:
  registrations:
    host: "0.0.0.0"
    port: 3001

  operations:
    host: "0.0.0.0"
    port: 3002

  vin_decoding:
    host: "0.0.0.0"
    port: 3003

  alpr:
    host: "0.0.0.0"
    port: 3004
