log:
  level: "debug"
  mode: "dev"

nats:
  host: "127.0.0.1"
  port: 4222
  user: "opencars"
  password: "opencars"

grpc:
  registrations:
    host: "0.0.0.0"
    port: 3001

  operations:
    host: "0.0.0.0"
    port: 3002

  vin_decoding:
    host: "0.0.0.0"
    port: 3003

  wanted:
    host: "0.0.0.0"
    port: 3004

http:
  statisfy:
    token: "example"
    secret: "example"
    host: "0.0.0.0"
    port: 8000
