log:
  level: "debug"
  mode: "dev"

grpc:
  registrations:
    host: "0.0.0.0"
    port: 3001

  operations:
    host: "0.0.0.0"
    port: 3002

  vin_decoding:
    host: "0.0.0.0"
    port: 3003

http:
  statisfy:
    token: "example"
    secret: "example"
    host: "0.0.0.0"
    port: 8000
